global:
  scrape_interval: 5s
  external_labels:
    monitor: 'Monitoring'
  

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - prometheus:9090

- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080